[15기 BOOMDOGGY팀] Add : 모델링 초기 버전 #1
wecode-bootcamp-korea/15-1st-boomdoggy-backend pull request #2
Opened 2020-12-16 10:33 UTC by Luceta

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
- 크게 4가지 앱에 따른 모델링 구성

- Users
->회원가입, 로그인, 마이페이지내 유저배송지 관리

- Products(참고: 총 제품이 treats(간식) 과 food(개사료)로 나눠짐 
-> 상품 상세정보, 이미지, 리뷰 , 구독과의 연계 여부

- Orders
로그인 후 마이페이지에 나타나는 주문이력(배송전, 배송중, 배송완료 등 상품 배송 상태 포함) / 제품 구독 관리
장바구니
 
- Payments
장바구니에서 주문창으로 넘어간 이후 배송정보(주소지, 전화번호 등) 입력
배송방법 및 배송비
주문 페이지 내 결제방법 (페이팔, 구글페이, 숍페이, 개인카드)
	
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

모델링은 같이 하여 boomback 브랜치에 합쳐놓았습니다. 
a-qurey리뷰 후 모델링은 좀더 간결하게 짜보았는데, 앱 기능별에 따라서 모델링을 나눠놨는데 ,
order랑 payment앱 기능에 맞게 잘 된 것이지 궁금합니다. 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-12-16 23:30 UTC, jamessoun93 requested changes

2020-12-16 23:30 UTC, jamessoun93 commented on orders/models.py
> +    discount_code       =   models.CharField(max_length = 100)
해당 오더에 적용된 할인코드를 기입하는 필드인가요? 모든 오더에 `discount_code` 가 존재할리는 없으니 그에 따라 한번 수정해보세요!

2020-12-16 23:30 UTC, jamessoun93 commented on orders/models.py
> +    payments_types       =   models.ForeignKey("payments.PaymentsType", on_delete = models.CASCADE,default=None)
- 여기 4개의 필드 모두 `default=None`을 주신 이유가 있을까요?
- 그리고 ForeignKey 필드는 복수형보다는 단수형이 맞으니 수정 부탁드립니다.

2020-12-16 23:30 UTC, jamessoun93 commented on orders/models.py
> +        db_table = "ordersstatus"
```suggestion
        db_table = "orders_status"
```

2020-12-16 23:30 UTC, jamessoun93 commented on orders/models.py
> +    quantity            =   models.CharField(max_length=200)
수량은 IntegerField 가 더 적합하겠죠? CharField로 선언해두면 말그대로 수량 필드에 일반 문자열이 들어가도 문제가 안된다는 뜻이니까요!

2020-12-16 23:30 UTC, jamessoun93 commented on orders/models.py
> +    payments_types       =   models.ForeignKey("payments.PaymentsType", on_delete = models.CASCADE,default=None)
여기도 컬럼명 전부 단수형으로 변경해주시고 default 문은 필요없어 보입니다.

2020-12-16 23:30 UTC, jamessoun93 commented on orders/models.py
> +    orders               =   models.ForeignKey("Orders", on_delete = models.CASCADE, default=None)
컬럼명 단수형으로 변경해주시고 default 문 없애주세요!

2020-12-16 23:30 UTC, jamessoun93 commented on orders/models.py
> +    weeks               =   models.CharField(max_length = 100)
구독 가능한 week 수를 담는 필드인가요? 그렇다면 IntegerField가 더 적합합니다.

2020-12-16 23:30 UTC, jamessoun93 commented on payments/models.py
> +    appartment_type     =   models.CharField(max_length = 500)
```suggestion
    apartment_type     =   models.CharField(max_length = 500)
```

2020-12-16 23:30 UTC, jamessoun93 commented on payments/models.py
> +    county_region       =   models.CharField(max_length = 100)
이런 정보들은 정규화가 필요해보입니다. 서울을 예로 들어, 누구는 "서울" 로 입력을하고 누구는 "Seoul" 로 입력을 한다면 필터할때는 다른값으로 분류됩니다. 그런 에러를 방지하기 위해 정규화 해주세요!

2020-12-16 23:30 UTC, jamessoun93 commented on payments/models.py
> +    delivery_method     =   models.CharField(max_length = 200)
이것도 몇가지 정해진 옵션들 중 고르게 될텐데 정규화 해주시면 좋을 것 같네요.

2020-12-16 23:30 UTC, jamessoun93 commented on payments/models.py
> +    validation_code     =   models.CharField(max_length = 50)
저희는 지금 연습단계여서 괜찮지만 신용카드정보처럼 민감한 정보는 절대 이렇게 그대로 저장하는법이 없습니다. 실제 서비스에서는 이런것만 전문으로하는 서비스를 이용하거나 아주 복잡한 알고리즘을 이용해 암호화해서 저장합니다. 그리고 보통 cvc 는 아무리 해당 계정에 묶여있는 카드정보라도 매번 결제당시 구매자가 직접 입력하게끔 하기때문에 불필요합니다.

2020-12-16 23:30 UTC, jamessoun93 commented on users/models.py
> +    annoymous       =   models.SmallIntegerField(default = 0)
```suggestion
    anonymous       =   models.SmallIntegerField(default = 0)
```

2020-12-16 23:30 UTC, jamessoun93 commented on users/models.py
> +    users           =   models.ForeignKey("Users", on_delete = models.CASCADE)
단수형으로 변경해주세요~

2020-12-16 23:30 UTC, jamessoun93 commented on products/models.py
> +    sale_rate       = models.IntegerField(default=0)
- ForeignKey 컬럼명은 단수형으로 변경해주세요
- 리뷰 점수는 리뷰 관련 테이블을 조회해서 종합해 구해오는정보이니 테이블에 컬럼으로 있을 필요는 없습니다.
- price 필드에 max_digits=3 에 decimal_places=2 면 모든 제품이 10달러 미만인가요?
- kilograms 도 숫자를 저장하는 필드이니 변경 필요합니다.
- quantity 도 마찬가지입니다.
- description 처럼 굉장히 길어질 수 있는 필드는 TextField 를 주시면 좋을 것 같네요.
- benefits 와 ingredients 는 정규화가 필요없나요?

2020-12-16 23:30 UTC, jamessoun93 commented on products/models.py
> +    images          = models.ManyToManyField(Products, through = "ImagesProducts")
Product와 Image를 M2M 관계로 지정해주셨는데, 같은 이미지들이 다른 Product의 이미지들이 될 수가 있나요?

2020-12-16 23:30 UTC, jamessoun93 commented on products/models.py
> +    reviews         = models.CharField(max_length =1000)
```suggestion
    content         = models.CharField(max_length =1000)
```

2020-12-16 23:30 UTC, jamessoun93 commented on products/models.py
> +    review_ratings  = models.IntegerField(default = 0)
3.5, 4.5 이런 값들은 허용을 안하나요?

2020-12-16 23:30 UTC, jamessoun93 commented on products/models.py
> +    img_url         = models.CharField(max_length = 500)
데이터베이스 컬럼은 이런걸 줄이지 않는게 좋습니다~
```suggestion
    image_url         = models.CharField(max_length = 500)
```

2020-12-16 23:30 UTC, jamessoun93 commented on products/models.py
> +    products         = models.ForeignKey("Products", on_delete = models.CASCADE)
단수형이요!

2020-12-17 01:45 UTC, markiron99 commented on orders/models.py
> +    quantity            =   models.CharField(max_length=200)
최초 수량을 IntegerField로 지정을 했었는데,
쇼핑몰 상품 페이지를 보니 수량이 단순하게 1,2,3,4 이렇게 표기되는 것이 아니라
Quantitiy : 1 / Quantity : 2 .... 이렇게 수량을 '하나의 메뉴'로 선택 할 수 있게 해두어서 CharField로 선택하였는데
그대로 IntegerField로 해도 무방한가요?!

2020-12-17 02:08 UTC, Luceta commented on orders/models.py
> +    payments_types       =   models.ForeignKey("payments.PaymentsType", on_delete = models.CASCADE,default=None)
처음 모델 셋팅에서는 모든 컬럼의 초기값이 none이 없었지만 마이그레이션을 하는 중에 테이블이 각 null값이 들어가서 바꿔줘야 한다고 자꾸 에러 문구가 떠서 저렇게 none으로 초기값을 재 설정해주니 마이그레이션 에러가 없어지고 다시 되어서 그렇게 하게 되었습니다. 수정시 다시 default값을 전부 빼고 마이그레이션을 해서 올리겠습니다.

2020-12-17 02:10 UTC, Luceta commented on orders/models.py
> +    discount_code       =   models.CharField(max_length = 100)
직접 주소 입력 후 신용카드 결제 넘어가기전, or 구글페이 등으로 바로 결제 넘어가기전의 주문창에서 할인코드가 옆에 입력하는 곳이 있는데, 그쪽까지 생각해서 모델링하였습니다.  아래 사진과  같이 옆쪽에 할인코드가 있는 사람은 넣고 없는 사람은 안넣는 식인지라 만들어 놓았습니다.
![image](https://user-images.githubusercontent.com/57941164/102434585-62928000-4058-11eb-8dcc-5519fd23685a.png)

2020-12-17 02:12 UTC, Luceta commented on orders/models.py
> +    payments_types       =   models.ForeignKey("payments.PaymentsType", on_delete = models.CASCADE,default=None)
모둔 컬럼 default 한 이유는 기존의 마이그레이션으로 인해 db상에 초기값이 null로 자동으로 설정되었고, 그리고 다시 마이그레이션 하는 과정에서 마이그레이션 에러로 저걸 지정해주니 에러가 사라져서 지정하였는데 모든 테이블 컬럼마다 재 수정하여 올리겠습니다.

2020-12-17 02:12 UTC, markiron99 commented on payments/models.py
> +    validation_code     =   models.CharField(max_length = 50)
네! 저희도 최초 모델링 할 때 민감한 신용카드 정보 관련해서 이야기가 있었다가,
우선 모델링 할 때 한 번에 넣고 빼기로 했었습니다!
바로 제거하겠습니다 :)

2020-12-17 02:14 UTC, markiron99 commented on orders/models.py
> +    payments_types       =   models.ForeignKey("payments.PaymentsType", on_delete = models.CASCADE,default=None)
원래 처음에는 정상적으로 default 를 주지 않았었는데,
마이그레이션을 진행하다가 계속 저 부분에 대한 에러가 계속 발생해서 넣었었고
다른 에러가 계속 나서 아예 데이터베이스를 없애고 다시 진행하였습니다!
이제 다시 원래대로 돌려놓겠습니다! :)

2020-12-17 02:14 UTC, markiron99 commented on orders/models.py
> +    payments_types       =   models.ForeignKey("payments.PaymentsType", on_delete = models.CASCADE,default=None)
네 바로 수정하겠습니다!

2020-12-17 02:14 UTC, markiron99 commented on orders/models.py
> +    orders               =   models.ForeignKey("Orders", on_delete = models.CASCADE, default=None)
네! 수정하겠습니다 :)

2020-12-17 02:15 UTC, Luceta commented on products/models.py
> +    images          = models.ManyToManyField(Products, through = "ImagesProducts")
이미지파일이 카테고리별 안의 상품들의 이미지와 그 각 상품별 리스트 안에서 클릭했을 시의 상세 페이지의 이미지에도 다른 이미지가 또 연결되어서 한 상품이 여러 이미지를 가질 수 가 있고 , 상품리스트에 보여지는 이미지가 그대로 상세리스트에도 쓰이다 보니  여러 이미지도 여러개의 카테고리를 가질 수 있기 때문에 many to many로 해주었습니다.

2020-12-17 02:16 UTC, Luceta commented on products/models.py
> +    review_ratings  = models.IntegerField(default = 0)
네 프론트랑 합의했는데 그러면 ui적용이나 그런 점이 힘들거 같다고 딱 별점이 1,2,3,4,5로 떨어지게 해줬으면 좋겠다고 하셔서 합의를 하여 딱 떨어지도록 integerField로 설정하였습니다.

2020-12-17 02:16 UTC, Luceta commented on products/models.py
> +    img_url         = models.CharField(max_length = 500)
네 처음이라 저희가 놓치는게 많았던거 같은데 , 잘 찾아보고 컨벤션 잘 지켜서 올리겠습니다.

2020-12-17 02:17 UTC, markiron99 commented on payments/models.py
> +    county_region       =   models.CharField(max_length = 100)
county는 주문창에서 선택할 수 있도록 메뉴가 구성되어있어서 정규화는 안 해도 될 것 같은데,
직접 입력해야 하는 address, apartment_type(apartment, suit, ect..) 와 city중
city는 말씀해주신 대로 정규화를 진행해야 할 것 같습니다 ㅠㅠ 진행하겠습니다!

2020-12-17 02:20 UTC, markiron99 commented on orders/models.py
> +    quantity            =   models.CharField(max_length=200)
IntegerField로 바꾸고 저 quantity 같은 글자는 ui에서 하는 것으로 생각하고 바꾸겠습니다!

2020-12-17 02:21 UTC, markiron99 commented on orders/models.py
> +    weeks               =   models.CharField(max_length = 100)
네, 수정하겠습니다!

2020-12-17 06:27 UTC, Luceta commented on products/models.py
> +    sale_rate       = models.IntegerField(default=0)
benefits와 ingredients 는 상세 설명과 같은 text나 표이기때문에 정규화가 필요 없고 ui에서만 보여주면 되는거 같습니다.

2020-12-17 08:27 UTC, Luceta commented on products/models.py
> +    products         = models.ForeignKey("Products", on_delete = models.CASCADE)
수정 완료 하였습니다

2020-12-17 11:21 UTC, lordmyshepherd requested changes

2020-12-17 11:21 UTC, lordmyshepherd commented on orders/models.py
> +    discount_code       =   models.CharField(max_length = 100)
discount code를 삭제해주세요.

2020-12-17 11:21 UTC, lordmyshepherd commented on payments/models.py
> +    delivery_method     =   models.CharField(max_length = 200)
```suggestion
    delivery_method_id     =   models.ForeignKey(max_length = 200)
```

class DeliveryMethod

2020-12-17 11:21 UTC, lordmyshepherd commented on payments/models.py
> +    validation_code     =   models.CharField(max_length = 50)
수정해주세요~

2020-12-17 12:08 UTC, Luceta commented on payments/models.py
> +    delivery_method     =   models.CharField(max_length = 200)
이 사이트가 요일마다 다른지는 모르겠지만 현재 지금 확인한결과 배송방법은 유일한 한가지 밖에 없는걸로 확인이 되었습니다.
옵션이 없으므로  테이블 그대로 사용하려고 합니다.

2020-12-18 01:45 UTC, lordmyshepherd commented
LGTM 👍

2020-12-18 01:45 UTC, merged