ADD: create signin,signup view in User app
wecode-bootcamp-korea/15-1st-boomdoggy-backend pull request #3
Opened 2020-12-18 10:11 UTC by markiron99

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입, 로그인 뷰 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- email('@', '.' 필수), password(문자1개, 숫자 8자 이상 16자 미만) 정규식 적용 및 password 암호화 완료
- 토큰 생성 기능 구현

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-12-20 11:11 UTC, ulfrid requested changes
수정 부탁 드립니다.

2020-12-20 11:11 UTC, ulfrid commented on users/views.py
> +                return JsonResponse({'message' : 'SUCCESS'}, status = 201)
```suggestion
            Users.objects.create(
                first_name  =   data['first_name'],
                last_name   =   data['last_name'],
                email       =   data['email'],
                password    =   hashed_password.decode('utf-8'),
            )

            return JsonResponse({'message' : 'SUCCESS'}, status = 201)
```
줄일 수 있는 else는 제거 해주세요!

2020-12-20 11:11 UTC, ulfrid commented on users/views.py
> +            else :
마찬가지로 제거하고 아래줄 코드 한탭 당겨주세요.

2020-12-20 11:11 UTC, ulfrid commented on users/views.py
> +                return JsonResponse({'message' : "THIS_USER_DOES_NOT_EXIST"}, status = 401)
```suggestion
                return JsonResponse({'message' : 'INVALID_USER'}, status = 401)
```
너무 친절하니까 간단하게 만들어주세요

2020-12-20 11:11 UTC, ulfrid commented on users/views.py
> +                return JsonResponse({'message' : 'PASSWORD_IS_NOT_VALID'}, status = 400)
```suggestion
                return JsonResponse({'message' : 'INVALID_PASSWORD'}, status = 401)
```
간단하게 코드화 해주세요!

2020-12-20 11:11 UTC, ulfrid commented on users/views.py
> +                return JsonResponse({'messages' : 'PLEASE_INSERT_YOUR_NAME'}, status = 400)
```suggestion
                return JsonResponse({'messages' : 'PLEASE_INSERT_YOUR_NAME'}, status = 400)
```
이 메세지를 프론트가 그대로 유저에게 전달하는게 아니라면 에러 메세지는 간단히 코드화 해주세요

2020-12-20 11:11 UTC, ulfrid commented on users/views.py
> +                return JsonResponse({'message' : 'INVALID_ID'}, status = 401)
```suggestion
                return JsonResponse({'message' : 'INVALID_EMAIL'}, status = 400)
```

2020-12-20 11:11 UTC, ulfrid commented on users/views.py
> +                return JsonResponse({'message' : 'INVALID_PASSWORD'}, status = 401)
```suggestion
                return JsonResponse({'message' : 'INVALID_PASSWORD'}, status = 400)
```

2020-12-21 08:51 UTC, markiron99 commented on users/views.py
> +                return JsonResponse({'message' : 'SUCCESS'}, status = 201)
수정 반영 했습니다!

2020-12-21 08:51 UTC, markiron99 commented on users/views.py
> +            else :
수정 반영 했습니다!

2020-12-21 08:51 UTC, markiron99 commented on users/views.py
> +                return JsonResponse({'message' : "THIS_USER_DOES_NOT_EXIST"}, status = 401)
수정 반영 했습니다!

2020-12-21 08:51 UTC, markiron99 commented on users/views.py
> +                return JsonResponse({'message' : 'PASSWORD_IS_NOT_VALID'}, status = 400)
수정 반영 했습니다!

2020-12-21 08:51 UTC, markiron99 commented on users/views.py
> +                return JsonResponse({'messages' : 'PLEASE_INSERT_YOUR_NAME'}, status = 400)
수정 반영 했습니다!

2020-12-21 08:52 UTC, markiron99 commented on users/views.py
> +                return JsonResponse({'message' : 'INVALID_ID'}, status = 401)
수정 반영 했습니다!

2020-12-21 08:52 UTC, markiron99 commented on users/views.py
> +                return JsonResponse({'message' : 'INVALID_PASSWORD'}, status = 401)
수정 했습니다!

2020-12-21 13:13 UTC, lordmyshepherd commented
LGTM 👍

2020-12-21 13:14 UTC, merged