Feature/product list
wecode-bootcamp-korea/15-1st-boomdoggy-backend pull request #4
Opened 2020-12-20 15:07 UTC by Luceta

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)

- 상품 리스트 뷰 기능 구현( 카테고리 2개중 하나 완료 나머지 푸쉬 예정)
- 주말 동안 모델링 변경( 구독 관련 사항이 모델링이 너무 복잡하고 어려워 구독 기능을 빼면서 전체 모델링 수정)

## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

-product table과 image table에서 각각 데이터를 꺼내와서 프론트 request에 맞춰서
reponse에 응답 해줌.(이미지 2개, 상품 타이틀과 가격, 재고현황, 세일 현황 )

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-12-21 02:29 UTC, lordmyshepherd requested changes

2020-12-21 02:29 UTC, lordmyshepherd commented on products/views.py
> +class TreatViews(View):
아래 모든 View의 코드가 중복됩니다.
`하나의 View`로 작성해주시고, filter 기능은 `query string`을 이용해서 구현해주세요~
```
class TreatViews(View)
class FoodViews(View)
class AdultFoodViews(View)
class PuppyFoodViews(View)
class SuperFoodViews(View)
class LightFoodViews(View)

```

2020-12-21 02:29 UTC, lordmyshepherd commented on products/urls.py
> +    path('/light-food',LightFoodViews.as_view(), name="light-foods"),
엔드포인트는 하나로 구현해주세요.
products/views.py 리뷰를 참고해주세요~

2020-12-22 01:34 UTC, Luceta commented on products/urls.py
> +    path('/light-food',LightFoodViews.as_view(), name="light-foods"),
하나의 엔드포인트로 구현 완료 하였습니다.

2020-12-22 01:34 UTC, Luceta commented on products/views.py
> +class TreatViews(View):
하나의 엔드포인트로 구성하고 query string으로 바꾸어 수정하였습니다.

2020-12-22 05:54 UTC, lordmyshepherd requested changes

2020-12-22 05:54 UTC, lordmyshepherd commented on products/views.py
> +            return JsonResponse({"products_list":products_list}, status=200)
[중요] 같은 코드가 중복되네요! 하나의 로직으로 합쳐주세요~

2020-12-22 05:54 UTC, lordmyshepherd commented on products/views.py
> +            treats = Categories.objects.get(name="treats")
get() 호출에 대한 에러 처리가 안되어 있습니다.

2020-12-22 05:54 UTC, lordmyshepherd commented on products/views.py
> +        products = Products.objects.get(id=product_id)
```suggestion
        product = Products.objects.get(id=product_id)
```

2020-12-22 05:54 UTC, lordmyshepherd commented on products/views.py
> +            "sub_image"     : Images.objects.filter(product_id=product_id).last().image_url,
Product 객체에서부터 접근해서 image_url을 조회할 수 있도록 코드를 수정해주세요~

2020-12-22 05:54 UTC, lordmyshepherd commented on products/views.py
> +            "category"      : Categories.objects.get(id=products.category_id).name,
마찬가지로 Product 객체에서 접근해서 name을 가져올 수 있도록 코드를 수정해주세요~

2020-12-22 05:54 UTC, lordmyshepherd commented on products/views.py
> +        return JsonResponse({"products_detail":data}, status=201)
GET 요청에 맞는 status code를 return 해주세요.

2020-12-22 05:54 UTC, lordmyshepherd commented on products/views.py
> +        review = Review.objects.all()
```suggestion
        reviews = Review.objects.all()
```

2020-12-22 05:54 UTC, lordmyshepherd commented on products/views.py
> +        }for i in range(len(review))]
range 함수를 사용하지 않고 구현해주세요.

2020-12-22 12:54 UTC, Luceta commented on products/views.py
> +        return JsonResponse({"products_detail":data}, status=201)
수정완료하였습니다.

2020-12-22 12:59 UTC, Luceta commented on products/views.py
> +        review = Review.objects.all()
수정완료 하였습니다.

2020-12-22 13:18 UTC, Luceta commented on products/views.py
> +        products = Products.objects.get(id=product_id)
수정 완료하였습니다.

2020-12-22 13:51 UTC, Luceta commented on products/views.py
> +            "sub_image"     : Images.objects.filter(product_id=product_id).last().image_url,
역참조로 호출하기를 통해 수정 완료 하였습니다.

2020-12-22 14:46 UTC, Luceta commented on products/views.py
> +            "category"      : Categories.objects.get(id=products.category_id).name,
역참조로 호출하기를 통해 수정 완료 하였습니다.

2020-12-22 14:58 UTC, Luceta commented on products/views.py
> +        }for i in range(len(review))]
수정완료하였습니다.

2020-12-22 15:56 UTC, Luceta commented on products/views.py
> +            treats = Categories.objects.get(name="treats")
수정완료하였습니다.

2020-12-22 16:17 UTC, Luceta commented on products/views.py
> +            return JsonResponse({"products_list":products_list}, status=200)
수정완료 하였습니다.

2020-12-22 16:30 UTC, lordmyshepherd requested changes

2020-12-22 16:30 UTC, lordmyshepherd commented on products/views.py
> +                "category"      : Categories.objects.get(id=product.category_id).name,
연관된 테이블에 아래와 같이 인스턴스 속성에 접근해서 데이터를 가져올 수 있습니다!
main_image, sub_image 도 아래와 같이 product부터 접근해서 가져와주세요~
```suggestion
                "category"      : product.category.name,
```

2020-12-22 16:30 UTC, lordmyshepherd commented on products/views.py
> +        review = Review.objects.all()
수정이 안되었습니다!
.all()을 호출하면 리스트가 반환되므로 `reviews` 복수형으로 작성해주세요!

2020-12-22 16:30 UTC, lordmyshepherd commented on products/views.py
> +        }for i in review]
```suggestion
        review_list = [{
            "id"                : review.id,
            "name"              : review.name,
            "image"             : review.image_url,
            "content"           : review.content,
            "date"              : review.created_at,
            "content_rating"    : review.content_rating,
        }for review in reviews]
```

2020-12-22 16:30 UTC, lordmyshepherd commented on products/views.py
> +        "sale_rate"     : products[i].sale_rate.sale_rate} for i in range(len(products))]
아래와 같이 range를 사용하지 않고 구현해주세요!
```suggestion
        "sale_rate"     : products[i].sale_rate.sale_rate} for i in range(len(products))]
```

2020-12-22 16:55 UTC, Luceta commented on products/views.py
> +                "category"      : Categories.objects.get(id=product.category_id).name,
네 수정완료하였습니다.

2020-12-22 17:12 UTC, Luceta commented on products/views.py
> +                "category"      : Categories.objects.get(id=product.category_id).name,
수정 완료 했습니다.

2020-12-23 06:10 UTC, Luceta commented on products/views.py
> +        "sale_rate"     : products[i].sale_rate.sale_rate} for i in range(len(products))]
수정완료하엿습니다.

2020-12-23 09:49 UTC, lordmyshepherd requested changes

2020-12-23 09:49 UTC, lordmyshepherd commented on orders/migrations/0001_initial.py
> +>>>>>>> 14180b79a2f88474d8654349a4d07aa951458829
한별님 conflict 해결해주세요!

2020-12-23 09:49 UTC, lordmyshepherd commented on orders/migrations/0001_initial.py
> +=======
여기도 컨플릭트 해결해주세요!

2020-12-23 09:49 UTC, lordmyshepherd commented on orders/migrations/0001_initial.py
> +>>>>>>> 14180b79a2f88474d8654349a4d07aa951458829
여기도 conflict 해결해주세요!

2020-12-23 09:49 UTC, lordmyshepherd commented on orders/migrations/0001_initial.py
> +<<<<<<< HEAD
conflict 해결해주세요.

2020-12-23 09:49 UTC, lordmyshepherd commented on orders/migrations/0001_initial.py
> +=======
conflict 해결해주세요!

2020-12-23 10:08 UTC, Luceta commented on orders/migrations/0001_initial.py
> +=======
메인 브랜치로 이동후 다시 전부 해결하였습니다.

2020-12-23 10:18 UTC, lordmyshepherd approved these changes

2020-12-23 10:45 UTC, lordmyshepherd commented
LGTM 👍

2020-12-23 11:56 UTC, merged